



GET  http://localhost:3000/sales_order

###
GET  http://localhost:3000/sales_order?id=16



###
POST http://localhost:3000/sales_order
Content-Type: "application/json"

{
   "client": {"id":1},
   "productsOrderLines":[{"productId":22,"qty":4,"price":9,"total":36},
   {"productId":14,"qty":5,"price":9,"total":40},
   {"productId":16,"qty":5,"price":10,"total":50}],
   "debit":40
}
