



GET  http://localhost:3000/sales_order

###
GET  http://localhost:3000/sales_order?id=93

###
GET  http://localhost:3000/sales_order?cid=1


###
GET  http://localhost:3000/sales_order?from=2021-06-21&to=2021-06-22

###
GET  http://localhost:3000/sales_order?cid=2&from=2021-06-21&to=2021-06-22


###
POST http://localhost:3000/sales_order
Content-Type: "application/json"

{
   "client": {"id":1},
   "productsOrderLines":[{ "productId":21, "qty":1, "price":9, "total" :36},
   {"productId":23, "qty" :2000,"price":9,"total" :40}],
   "debit":40
}
