



GET  http://localhost:3000/sales_order

###
GET  http://localhost:3000/sales_order?id=93



###
POST http://localhost:3000/sales_order
Content-Type: "application/json"

{
   "client": {"id":1},
   "productsOrderLines":[{ "productId":21, "qty":1, "price":9, "total" :36},
   {"productId":23, "qty" :3,"price":9,"total" :40}],
   "debit":40
}
